//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Data&gt;
        ///  &lt;Bookings&gt;
        ///    &lt;Booking&gt;
        ///      &lt;BookingId&gt;1&lt;/BookingId&gt;
        ///      &lt;FirstName&gt;Anna&lt;/FirstName&gt;
        ///      &lt;LastName&gt;Smith&lt;/LastName&gt;
        ///      &lt;RoomId&gt;1&lt;/RoomId&gt;
        ///      &lt;CheckInDate&gt;2025-07-19&lt;/CheckInDate&gt;
        ///      &lt;CheckOutDate&gt;2025-07-21&lt;/CheckOutDate&gt;
        ///      &lt;RequestId&gt;1&lt;/RequestId&gt;
        ///      &lt;IsRecurring&gt;false&lt;/IsRecurring&gt;
        ///      &lt;RecurrencePattern&gt;None&lt;/RecurrencePattern&gt;
        ///    &lt;/Booking&gt;
        ///    &lt;Booking&gt;
        ///      &lt;BookingId&gt;2&lt;/BookingId&gt;
        ///      &lt;FirstName&gt;David&lt;/FirstName&gt;
        ///      &lt;LastName&gt;Lee&lt;/LastName&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialBookingsXML {
            get {
                return ResourceManager.GetString("InitialBookingsXML", resourceCulture);
            }
        }
    }
}
